### ISSUE TITLE
Tests (and application) fails with Node 10.x

### ISSUE THREAD

**Issue by Nantris** [jdiamond/chrome-native-messaging#8]
**`node test.js` results in:**
```
TAP version 13
# Input
(node:9368) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
ok 1 should be equal
C:\Projects\NativeMessaging\New\node_modules\tape\index.js:75
        throw err
        ^

TypeError: Cannot read property 'foo' of null
    at Input.<anonymous> (C:\Projects\NativeMessaging\New\test.js:18:21)
    at Input.emit (events.js:182:13)
    at emitReadable_ (_stream_readable.js:534:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Tests work with Node 8.11. I haven't tried running the application though.

**Comment by Nantris** [comment]
This bit of code seems to be run twice in the test with Node 10.x. Perhaps the `readable` event is being fired twice somehow?

https://github.com/jdiamond/chrome-native-messaging/blob/master/test.js#L16-L19
